---
- name: "Get list of instances"
  hosts: "localhost"  
  tasks:
  - name: "Get instance"
    shell: gcloud compute instances list
#   command: gcloud compute instances list
    register: list
  - name: Print the all instances
    debug:
    msg: "All instance: {{ list }}"